### PR TITLE
[EV-1171][EV-1195] Update dependency of dashcore-lib to new prerelease 1.0.0-alpha.22

### PR DESCRIPTION
**Pull request by Cofresi**
**Issue being fixed or implemented**
This is for the imminent 13.0 mainnet launch. Updated dependency of dashcore-lib to new prerelease 1.0.0-alpha.2
**What was done**
as above
**What has been tested**
unit tests
**What needs to be tested**
will test this develop version on insight api testnet install. Once deemed stable will bump major version, push git tag, push to master and make new npm release 5.0.0
**Code Coverage**
n/a

### CODE REVIEW

**Comment by Cofresi** [comment]
Will wait a few more days before merging to see if 1.0.0-alpha.22 is working stable with latest RC of 0.13 release

**Comment by akfranco** [comment]
@Cofresi has it proven to be working with the latest release?

**Comment by Cofresi** [comment]
@KamuelaFranco yes, but I'd like to wait just a little longer to go through all the different spork activation steps of the release testing before merging. I'll ping you once it's ready to merge.
@KamuelaFranco This has been running good for more than a week now. I think we can go for it.

**Review by akfranco — APPROVED** [review]
utACK

**Pull request merged**
