### PR TITLE
Release v5.0.0

### PR DESCRIPTION
**Pull request by Cofresi**
**Issue being fixed or implemented**
Bumped dashcore-lib dependency to latest release. Resolved conflicts and merged master back into develop. Bumped version to 5 (breaking changes aka special transactions with launch of 13.0). Also bumped other dependencies and dev dependencies. In case of mocha, sinon and chai I bumped as far as I could without breaking the existing unit tests. In case we want to ensure using the latest versions of those dev deps, tests should be fixed in a later PR.
**What was done**
see above
**What has been tested**
unit tests
**What needs to be tested**
n/a
**Code Coverage**
n/a

**Comments**
Once this is in develop we should test this release with some special tx blocks on testnet insight-api and if successful merge develop to master, tag release and publish to npm at the same time as 0.13 goes live. It would be cool to get rid of the develop branch after that.
Needs https://github.com/dashevo/dashcore-lib/pull/94 and https://github.com/dashevo/dashcore-lib/pull/95 to be merged first

### CODE REVIEW

**Review by akfranco — DISMISSED** [review]
utACK

**Comment by nmarley** [comment]
@Cofresi Won't we need to update the dashcore-lib version once v0.16 is released? If yes, could we wait for that and then bump the version in this PR?

**Comment by Cofresi** [comment]
>@Cofresi Won't we need to update the dashcore-lib version once v0.16 is released? If yes, could we wait for that and then bump the version in this PR?

Yes, that would be prefered. Added a do-not-merge label.

**Comment by Cofresi** [comment]
>@Cofresi Won't we need to update the dashcore-lib version once v0.16 is released? If yes, could we wait for that and then bump the version in this PR?

Yes, let's do that. Adding a "do-not-merge"-label.

**Review by nmarley — APPROVED** [review]
utACK

**Pull request merged**
